# Generated by Django 4.0 on 2021-12-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('firstName', models.CharField(blank=True, max_length=150, null=True)),
                ('lastName', models.CharField(blank=True, max_length=150, null=True)),
                ('password', models.CharField(max_length=150)),
                ('about', models.TextField(blank=True, max_length=500, null=True)),
                ('role', models.CharField(choices=[('user', 'user'), ('admin', 'admin')], default='user', max_length=5)),
                ('isActive', models.BooleanField(default=True)),
                ('isVerified', models.BooleanField(default=False)),
                ('emailToken', models.CharField(blank=True, max_length=150, null=True)),
                ('emailTokenExpireDate', models.DateTimeField(blank=True, null=True)),
                ('resetToken', models.CharField(blank=True, max_length=150, null=True)),
                ('resetTokenExpireDate', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
