# Generated by Django 4.0 on 2021-12-09 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('firstName', models.CharField(blank=True, max_length=150, null=True)),
                ('lastName', models.CharField(blank=True, max_length=150, null=True)),
                ('password', models.CharField(max_length=150)),
                ('about', models.TextField(blank=True, max_length=500, null=True)),
                ('phone_number', models.TextField(blank=True, max_length=500, null=True)),
                ('address', models.TextField(blank=True, max_length=150, null=True)),
                ('city', models.TextField(blank=True, max_length=150, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], max_length=6, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('isVerified', models.BooleanField(default=False)),
                ('emailToken', models.CharField(blank=True, max_length=150, null=True)),
                ('emailTokenExpireDate', models.DateTimeField(blank=True, null=True)),
                ('resetToken', models.CharField(blank=True, max_length=150, null=True)),
                ('resetTokenExpireDate', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.category')),
            ],
        ),
    ]
