# Generated by Django 4.0 on 2021-12-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_musician_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
